Causation paper by DOK
AleksandrLiebert/aleksandrliebert.github.io pull request #1
Opened 2021-08-06 08:56 UTC by shappiron

no title picture for this paper, please, add it

2021-08-06 09:27 UTC, AleksandrLiebert requested changes

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +# Каузация
Название статьи подтянется из json  в статье этот заголовок не указывается

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +# Correlation does not imply causation!
Это что-то вроде подзаголовка, но ты выделил как заголовок, поправь

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +***Каузация*** - она же **причинность**, она же **обусловленность**. Термин с помощью которого обозначают необходимую связь между двумя событиями цепочкой **причина** → **следствие**.
Почему "необходимую" кому необходимую? Мне видится это определение перегруженным, по моему, достаточно сказать, что этим термином обозначают причино-следственную связь между событиями, всем будет понятно.

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +***Корреляция*** - **взаимосвязь** двух событий, как правило, под ней подразумевают статистическую взаимосвязь событий. При этом, ограничение на "необходимость" снимается, подчеркивая тем самым, что
А что бывает не статистическая корреляция? Если нет, то это определение тоже следует упростить.

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +- [Пример](https://wikiboard.ru/wiki/Correlation_does_not_imply_causation#Examples_of_illogically_inferring_causation_from_correlation) ошибочного вывода каузации из корреляции
Пример выделен как элемент списка, если тебе нужен превью файла, он есть здесь. Если тебе нужно выделение текста схожее со спойлером то юзай цитаты в md.

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +Какого же отношение между корреляцией и каузацией? Для ответа на этот вопрос проще всего сначала рассмотреть отношение между каузацией и истиной. Вспоминая основную аксиому истины, а именно что: "**А
То что нет абсолютной истины, аксиома только в твоей статье о истине, в трактате целая статья посвящена этому доказательству.

2021-08-06 09:27 UTC, AleksandrLiebert commented on content/causation.md
> +Таким образом, далее эта статья будет посвящена тем, кто избрал первый путь в постижении каузации. К счастью, теория истины благоволит тем, кто выбрал эту дорогу, предлагая несколько общих соображени
тут уместно сказать просто "более безошибочно" подразумевая, что ошибки быть всё равно могут, так более читаемо

2021-08-07 13:34 UTC, shappiron commented on content/causation.md
> +***Каузация*** - она же **причинность**, она же **обусловленность**. Термин с помощью которого обозначают необходимую связь между двумя событиями цепочкой **причина** → **следствие**.
Я специально делаю акцент на "необходимости", чтобы подчеркнуть отличие каузации от корреляции, которое состоит именно в этой необходимости (или неизбежности)

2021-08-07 13:40 UTC, shappiron commented on content/causation.md
> +***Корреляция*** - **взаимосвязь** двух событий, как правило, под ней подразумевают статистическую взаимосвязь событий. При этом, ограничение на "необходимость" снимается, подчеркивая тем самым, что
Да, в языке мы можем использовать слово Корреляция в отношении одного единственного наблюдения, здесь (возможно напрасно) я понимаю под статистикой всё же многие систематические наблюдения.

2021-08-07 13:52 UTC, shappiron commented on content/causation.md
> +Какого же отношение между корреляцией и каузацией? Для ответа на этот вопрос проще всего сначала рассмотреть отношение между каузацией и истиной. Вспоминая основную аксиому истины, а именно что: "**А
Но ты там ничего не доказал, ты просто привёл несколько рассуждений о неполноте поступаемой информации, которую в науке решают с помощью моделирования.

2021-08-07 13:54 UTC, shappiron commented on content/causation.md
> +Таким образом, далее эта статья будет посвящена тем, кто избрал первый путь в постижении каузации. К счастью, теория истины благоволит тем, кто выбрал эту дорогу, предлагая несколько общих соображени
"Более безошибочно" - звучит косноязычно. Заменил на 

> по тому, как практически (с некоторыми оговорками) безошибочно устанавливать каузальную

2021-08-14 14:34 UTC, shappiron commented on content/causation.md
> +# Correlation does not imply causation!
Корреляция ещё не есть каузация!

2021-08-14 14:35 UTC, AleksandrLiebert commented on content/causation.md
> +# Correlation does not imply causation!
Вернуть заголовки первого уровня и перевести первый заголовок

2022-06-17 11:26 UTC, closed without merging